# Machine Learning

## using Scikit-Learn

---

# Table of Contents

### 1. Learning Classification 

- [Supervised-Learning (지도 학습)](#supervised_learning)
- [UnSupervised-Learning (비지도 학습)](#unsupervised_learning)
- [einforcement-Learning (강화 학습)](#reinforcement_learning)

## 2. Supervised-Learning

- Regression (회귀)
- Classification (분류)

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

---

# Learning Classification

<a id="supervised_learning"></a>
## Supervised Learning

트레이닝 세트(training set) 와 각각에 대한 목표 값(target value)이 제공되고, 이 제공된 데이터 세트를 통해 모든 입력 값에 대해 정답을 유추해 낼 수 있도록 일반화 시킨다. 이것은 또한 예제를 통한 학습이라고도 불린다.

---

<a id="unsupervised_learning"></a>
## UnSupervised Learning

정답이나 목표값이 제공되지 않는 경우, 알고리즘이 정답을 제공하기보다는 예제 간에 유사점을 찾아내고, 이를 통해서 분류 체계를 확립할 수 있게 한다. 통계학적인 비지도학습은 밀도 추정이라고 한다.

---

<a id="reinforcement_learning"></a>
## Reinforcement Learning

지도학습과 비지도학습의 중간 정도에 해당한다. 알고리즘이 출력하는 값에 어느 것이 틀렸는지 알려 주지만, 이를 어떻게 고쳐야 하는지는 알려주지 않는다. 그래서 알고리즘이 스스로 여러 방법을 시도하여 정답을 찾도록 한다. 강화학습은 시험지의 점수는 매기지만 이를 어떻게 발전시킬 것인지는 스스로 찾게 하는 것으로 비판을 통한 학습 이라고도 불린다.

---

<br><br><br>
## Scikit Learn example

In [1]:
import pandas as pd

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.data.shape)
print(iris.data)

(150, 4)
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [

In [6]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'],
      dtype='<U10')

In [8]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
X = iris.data
y = iris.target

In [17]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

<br>
## Scikit Learn example

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
knn = KNeighborsClassifier(n_neighbors=1)

In [13]:
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [14]:
knn.predict([3, 5, 4, 2])

ValueError: Expected 2D array, got 1D array instead:
array=[3 5 4 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]

In [ ]:
knn.predict(X_new)

In [ ]:
res = knn.predict(X)

<br>
## Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logreg = LogisticRegression()

In [ ]:
logreg.fit(X, y)

In [ ]:
logreg.predict(X)

<br>
## Accuracy evaluation

In [ ]:
from sklearn import metrics

In [ ]:
y_pred = logreg.predict(X)

print(len(y_pred))

In [ ]:
accuracy = metrics.accuracy_score(y, y_pred)

print(accuracy)

## KNN (K=5)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X, y)

y_pred = knn.predict(X)

accuracy = metrics.accuracy_score(y, y_pred)

In [ ]:
print(accuracy)

In [ ]:
y_pred

## KNN (K=1)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=1)

knn.fit(X, y)

y_pred = knn.predict(X)

accuracy = metrics.accuracy_score(y, y_pred)

In [ ]:
print(accuracy)

In [ ]:
y_predknn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X, y)

y_pred = knn.predict(X)

accuracy = metrics.accuracy_score(y, y_pred)

<br>
## Evaluation : Train/test split

In [ ]:
from sklearn.cross_validation import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.6)

In [ ]:
print(len(x_train), '-', len(x_test))
print(len(y_train), '-', len(y_test))

In [ ]:
logreg = LogisticRegression()

logreg.fit(x_train, y_train)

In [ ]:
y_pred = logreg.predict(x_test)

In [ ]:
accuracy = metrics.accuracy_score(y_test, y_pred)

In [ ]:
print(accuracy)

<br>
## SVM

In [ ]:
from sklearn import datasets, svm

In [ ]:
digits = datasets.load_digits()

In [ ]:
print(digits.data)

In [ ]:
x, y = digits.data[:-1], digits.target[:-1]

In [ ]:
x

In [ ]:
y

In [ ]:
clf = svm.SVC(gamma=0.001, C=100)

In [ ]:
pred = clf.fit(x, y)

In [ ]:
pred

In [ ]:
pred = digits.data[-1]

In [ ]:
pred