# MultiVariate Linear Regression

---

In [2]:
from sklearn.linear_model import Linear# Machine LearningRegression

import numpy as np

reference
https://stackoverflow.com/questions/11479064/multiple-linear-regression-in-python

In [3]:
x1 = np.matrix([[1,1],[1,2]])
"""
x1 [1, 1
    1, 2]
"""
x2 = np.matrix([[1],[1]])
"""
x2 = [1
      1]
"""

'\nx2 = [1\n      1]\n'

In [4]:
res = np.dot(x1,x2)

print(res)

[[2]
 [3]]


In [5]:
x1 = np.matrix([[1,1],[1,2]])
x2 = np.matrix([[2],[1]])

In [6]:
res = np.dot(x1,x2)

print(res)

[[3]
 [4]]


In [7]:
X = np.matrix([
    [1,1,5],
    [2,2,4],
    [3,2,3],
    [4,3,2],
    [5,5,1],
])

y = np.matrix([
    [-2],
    [2],
    [5],
    [9],
    [14],
])

In [15]:
reg = LinearRegression(fit_intercept=False)   # intercept is 0, if True means not 0

reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

### slope of each variable

In [16]:
print(reg.coef_)

[[ 2.  1. -1.]]


### intercept of line

In [17]:
print(reg.intercept_)

0.0
